type LoginPayload {
  accessToken: String!
  user: User!
}

type RefreshTokensPayload {
  accessToken: String!
}

extend type Mutation {
  register(input: RegisterInput!): RegisterPayload!
  verifyOTP(email: String!, otp: String!): VerifyOTPPayload!
  resendOTP(email: String!): ResendOTPPayload!
  login(input: LoginInput!): LoginPayload!
  refreshTokens: RefreshTokensPayload!        
  logout: Boolean!
}

input RegisterInput {
  email: String!
  password: String!
  phoneNumber: String
}

input LoginInput {
  email: String!
  password: String!
}

type RegisterPayload {
  message: String!
  email: String!
}

type VerifyOTPPayload {
  success: Boolean!
  message: String!
}

type ResendOTPPayload {
  success: Boolean!
  message: String!
  expiresAt: DateTime!
}