ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_REFUNDED';

ALTER TABLE "Payment"
ADD COLUMN "refundedAmount" DECIMAL(10,2) NOT NULL DEFAULT 0,
ADD COLUMN "refundPolicy" TEXT,
ADD COLUMN "refundedAt" TIMESTAMP(3);
