enum PaymentStatus {
  PENDING
  PAID
  FAILED
  REFUNDED
}

type PaymentMethod {
  id:   ID!
  name: String!
}

type Payment {
  id:            ID!
  bookingId:     ID!
  amount:        Float!
  status:        PaymentStatus!
  stripeId:      String
  paymentMethod: PaymentMethod
  createdAt:     DateTime!
  updatedAt:     DateTime!
}

type CheckoutSession {
  url:       String!
  sessionId: String!
}

type PaginatedPayments {
  items:    [Payment!]!
  pageInfo: PageInfo!
}

extend type Query {
  payment(id: ID!):                        Payment
  paymentByBooking(bookingId: ID!):        Payment
  myPayments(pagination: PaginationInput): PaginatedPayments!
  payments(pagination: PaginationInput):   PaginatedPayments!
}

extend type Mutation {
  createCheckoutSession(bookingId: ID!): CheckoutSession!
  refundPayment(paymentId: ID!):         Payment!
  mockFinalizePayment(bookingId: String!, success: Boolean!): Payment!
}